src/main/java/ru/kislyak/projects/controler/UserController.java
package ru.kislyak.projects.controler;

import ru.kislyak.projects.pojos.Role;
import ru.kislyak.projects.pojos.User;
import ru.kislyak.projects.service.UserService;
import ru.kislyak.projects.utils.JsfUtils;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.List;

@ManagedBean(name = "userController")
@ViewScoped
public class UserController implements Serializable {
    @ManagedProperty("#{userService}")
    private UserService userService;

    private User selectedUser;
    private Role selectedRole;
    private List<User> usersList;

    @PostConstruct
    private void init() {
        this.usersList = userService.getUsersList();
    }

    //  метод удаляет запись из БД
    public void deleteUser() {
        userService.deleteUser(selectedUser);
        selectedUser = null;
        JsfUtils.addSuccessMessage("Пользователь удален!");
        init();
    }

    // метод обновляет данные пользователя
    public void updateUser() {
        userService.updateUserByAdmin(selectedUser, selectedRole.getId());
        JsfUtils.addSuccessMessage("Пользователь изменен!");
        selectedUser = null;
        selectedRole = null;
        init();
    }

    //  устанавливаем указатель менюшки на текущую роль
    public void prepareEditUser() {
        if (selectedUser.getRolename() != null) {
            this.selectedRole = selectedUser.getRolename();
        } else this.selectedRole = null;
    }

    //Запрашиваем список ролей для заполнения
    //выпадающего меню
    public List<Role> getAllRoles() {
        return userService.getAllRoles();
    }

    // Запрашиваем список пользователей из БД
    public List<User> getUsersList() {
        return this.usersList;
    }

    public User getSelectedUser() {
        return selectedUser;
    }

    public void setSelectedUser(User selectedUser) {
        this.selectedUser = selectedUser;
    }

    public Role getSelectedRole() {
        return selectedRole;
    }

    public void setSelectedRole(Role selectedRole) {
        this.selectedRole = selectedRole;
    }

    public void setUsersList(List<User> usersList) {
        this.usersList = usersList;
    }

    public void setUserService(UserService userService) {
        this.userService = userService;
    }
}

web/admin/AcceptNewUser.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="#{loginController.template}">
    <ui:define name="title">
        <h:outputText value="Подтверждение регистрации"/>
    </ui:define>
    <ui:define name="body">
        <div class="form-register">
            <h:form id="formAcceptNewUser">
                <p:panel id="acceptPanel" header="Подтверждение регистрации">
                    <h:panelGrid columns="2" rendered="#{acceptController.tempUser != null}" cellpadding="5">
                        <h:outputText value="Логин"/>
                        <h:outputText value="#{acceptController.tempUser.name}"/>

                        <h:outputText value="Фамилия"/>
                        <h:outputText value="#{acceptController.tempUser.lastname}"/>

                        <h:outputText value="Имя"/>
                        <h:outputText value="#{acceptController.tempUser.firstname}"/>

                        <h:outputText value="Отчество"/>
                        <h:outputText value="#{acceptController.tempUser.middlename}"/>

                        <h:outputText value="Роль"/>
                        <p:selectOneMenu value="#{acceptController.selectedRole}">
                            <f:selectItems value="#{userController.allRoles}" var="list" itemLabel="#{list.rolename}"
                                           itemValue="#{list.id}"/>
                        </p:selectOneMenu>

                        <h:outputText value="Активирован"/>
                        <p:selectBooleanCheckbox value="#{acceptController.tempUser.accepted}"/>

                        <f:facet name="footer">
                            <p:commandButton action="#{acceptController.acceptUser}" value="Подтвердить"/>
                            <p:commandButton action="#{acceptController.deleteUser}" value="Удалить"/>
                        </f:facet>
                    </h:panelGrid>
                </p:panel>
            </h:form>
        </div>
    </ui:define>
</ui:composition>

</html>

web/admin/AdminMenu.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

<ui:composition>
    <p:submenu label="Администрирование" expanded="true">
        <p:menuitem value="Пользователи" action="/admin/UserList" icon="ui-icon-menuitem"/>
    </p:submenu>
</ui:composition>
</html>

web/admin/AdminTemplate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<ui:composition template="/user/UserTemplate.xhtml">
    <ui:define name="title">
        <h:outputText value="Режим администратора"/>
    </ui:define>
    <ui:define name="left_menu">
        <h:form id="form_menu">
            <p:panelMenu>
                <ui:include src="/user/UserMenu.xhtml"/>
                <ui:include src="/admin/AdminMenu.xhtml"/>
            </p:panelMenu>
        </h:form>
    </ui:define>
</ui:composition>
</html>

web/admin/EditUser.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<ui:composition>

    <p:dialog id="UserEditDlg" widgetVar="UserEditDialog" modal="true" resizable="false" appendTo="@(body)"
              header="Редактировать данные о пользователе">
        <h:form id="UserEditForm">
            <h:panelGroup id="display">
                <h:panelGrid columns="2" rendered="#{userController.selectedUser != null}" cellpadding="5">
                    <h:outputText value="Логин"/>
                    <p:inputText value="#{userController.selectedUser.name}"/>

                    <h:outputText value="Пароль (Hash)"/>
                    <p:inputText value="#{userController.selectedUser.password}"/>

                    <h:outputText value="Фамилия"/>
                    <p:inputText value="#{userController.selectedUser.lastname}"/>

                    <h:outputText value="Имя"/>
                    <p:inputText value="#{userController.selectedUser.firstname}"/>

                    <h:outputText value="Отчество"/>
                    <p:inputText value="#{userController.selectedUser.middlename}"/>


                    <h:outputText value="Роль"/>
                    <p:selectOneMenu value="#{userController.selectedRole}" converter="omnifaces.SelectItemsConverter">
                        <f:selectItems value="#{userController.allRoles}" var="list" itemLabel="#{list.rolename}"/>
                    </p:selectOneMenu>

                    <h:outputText value="Активирован"/>
                    <p:selectBooleanCheckbox value="#{userController.selectedUser.accepted}"/>


                    <f:facet name="footer">
                        <p:commandButton actionListener="#{userController.updateUser}" value="Изменить"
                                         update="display,:formUserList:tableUsers"
                                         oncomplete="PF('UserEditDialog').hide();" style="margin: 5px"/>
                        <p:commandButton value="Отменить" onclick="PF('UserEditDialog').hide();"/>
                    </f:facet>
                </h:panelGrid>
            </h:panelGroup>
        </h:form>
    </p:dialog>

</ui:composition>
</html>

web/admin/UserList.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="#{loginController.template}">
    <ui:define name="title">
        <h:outputText value="Пользователи приложения"/>
    </ui:define>
    <ui:define name="body">
        <h:form id="formUserList">
            <p:dataTable id="tableUsers" value="#{userController.usersList}"
                         var="users"
                         rows="20"
                         paginator="true"
                         paginatorPosition="top"
                         paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="10,20,30,50"
                         resizableColumns="true"
                         lazy="false"
                         paginatorAlwaysVisible="false"
                         selectionMode="single"
                         rowKey="#{users.id}"
                         selection="#{userController.selectedUser}">

                <p:ajax event="rowSelect" update="deleteButton editButton"/>
                <p:ajax event="rowUnselect" update="deleteButton editButton"/>

                <f:facet name="header">
                    Пользователи приложения
                </f:facet>

                <p:column headerText="Логин">
                    <h:outputText value="#{users.name}"/>
                </p:column>
                <p:column headerText="Пароль (Hash)">
                    <h:outputText value="#{users.password}"/>
                </p:column>
                <p:column headerText="Фамилия">
                    <h:outputText value="#{users.lastname}"/>
                </p:column>
                <p:column headerText="Имя">
                    <h:outputText value="#{users.firstname}"/>
                </p:column>
                <p:column headerText="Отчество">
                    <h:outputText value="#{users.middlename}"/>
                </p:column>
                <p:column headerText="Роль">
                    <h:outputText value="#{users.rolename.rolename}"/>
                </p:column>
                <p:column headerText="Активирован">
                    <p:selectBooleanCheckbox value="#{users.accepted}"/>
                </p:column>
                <f:facet name="footer">

                    <p:commandButton id="editButton" icon="ui-icon-pencil" value="Редактировать"
                                     actionListener="#{userController.prepareEditUser}" update=":UserEditForm"
                                     oncomplete="PF('UserEditDialog').show()"
                                     disabled="#{empty userController.selectedUser}"/>

                    <p:commandButton id="deleteButton" icon="ui-icon-trash" value="Удалить"
                                     actionListener="#{userController.deleteUser}"
                                     update="growl,:formUserList:tableUsers,deleteButton"
                                     disabled="#{empty userController.selectedUser}">
                        <p:confirm header="Удаление записи"
                                   message="Вы действительно хотите удалить пользователя?"
                                   icon="ui-icon-alert"/>
                    </p:commandButton>
                </f:facet>
            </p:dataTable>
        </h:form>

        <ui:include src="/admin/EditUser.xhtml"/>
    </ui:define>
</ui:composition>

</html>