src/main/java/ru/kislyak/projects/controler/ProjectController.java
package ru.kislyak.projects.controler;

import ru.kislyak.projects.pojos.Designer;
import ru.kislyak.projects.pojos.Project;
import ru.kislyak.projects.service.ProjectService;
import ru.kislyak.projects.utils.JsfUtils;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.List;
import java.util.Locale;

@ManagedBean(name = "projectController")
@ViewScoped
public class ProjectController implements Serializable{
    @ManagedProperty("#{projectService}")
    private ProjectService projectService;

    private List<Project> projectsList;
    private Project tempProject;
    private int selectedDesigner;
    private List<Designer> allDesigners;

    // инициализируем список проектов и список проектировщиков
    //  Запрашиваем полный перечень проектировщиков из БД
    @PostConstruct
    private void init(){
        this.allDesigners=projectService.getAllDesigners();
        this.projectsList=projectService.getAllProjects();
        this.tempProject = null;
    }

    public List<Project> getProjectsList() {
        return this.projectsList;
    }

    // Инициализируем временное поле где будем хранить редактируемый/добавляемы проект
    public Project prepareAddProject() {
        tempProject = new Project();
        return tempProject;
    }

    // обновляем данные о проекте в БД
    public void update() {
        projectService.updateProject(tempProject, selectedDesigner);
        JsfUtils.addSuccessMessage("Проект изменен!");
        init();     //Освежаем список проектов
    }

    // устанавливаем положение селектбокса на текущего проектировщика
    public void prepareEditProject() {
        if (tempProject.getDesigner() != null) {
            this.selectedDesigner = tempProject.getDesigner().getId();
        } else this.selectedDesigner = 0;
    }

    // удаляем выбранный проект
    public void deleteProject() {
        projectService.deleteProject(tempProject);
        JsfUtils.addSuccessMessage("Проект удален!");
        init();     //Освежаем список проектов
    }

    // добавляем проект
    public void addProject() {
        projectService.addProject(tempProject,selectedDesigner);
        JsfUtils.addSuccessMessage("Проект добавлен!");
        init();     //Освежаем список проектов
    }

    //Запрашиваем фамилию текущего проектировщика
    public String getCurentDesignerLastname(){
        if (tempProject.getDesigner() != null) {
            int currId = tempProject.getDesigner().getId();
            for (Designer designer: allDesigners) {
                if (designer.getId()==currId){
                    return designer.getLastname();
                }
            }
        }
        return null;
    }

    public boolean filterByStatus(Object value, Object filter, Locale locale){
        return value.toString().toLowerCase().startsWith(filter.toString().toLowerCase());
    }

    public List<Designer> getAllDesigners() { return this.allDesigners;    }

    public void setAllDesigners(List<Designer> allDesigners) {
        this.allDesigners = allDesigners;
    }

    public Integer getSelectedDesigner() {
        return selectedDesigner;
    }

    public void setSelectedDesigner(Integer selectedDesigner) {
        this.selectedDesigner = selectedDesigner;
    }

    public Project getTempProject() {
        return tempProject;
    }

    public void setTempProject(Project tempProject) {
        this.tempProject = tempProject;
    }

    public void setProjectsList(List<Project> projectsList) {
        this.projectsList = projectsList;
    }

    public void setProjectService(ProjectService projectService) {
        this.projectService = projectService;
    }
}

src/main/java/ru/kislyak/projects/controler/UserController.java
package ru.kislyak.projects.controler;

import ru.kislyak.projects.pojos.Role;
import ru.kislyak.projects.pojos.User;
import ru.kislyak.projects.service.UserService;
import ru.kislyak.projects.utils.JsfUtils;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import java.io.Serializable;
import java.util.List;

@ManagedBean(name = "userController")
@ViewScoped
public class UserController implements Serializable {
    @ManagedProperty("#{userService}")
    private UserService userService;

    private User selectedUser;
    private Role selectedRole;
    private List<User> usersList;

    @PostConstruct
    private void init() {
        this.usersList = userService.getUsersList();
    }

    //  метод удаляет запись из БД
    public void deleteUser() {
        userService.deleteUser(selectedUser);
        selectedUser = null;
        JsfUtils.addSuccessMessage("Пользователь удален!");
        init();
    }

    // метод обновляет данные пользователя
    public void updateUser() {
        userService.updateUserByAdmin(selectedUser, selectedRole.getId());
        JsfUtils.addSuccessMessage("Пользователь изменен!");
        selectedUser = null;
        selectedRole = null;
        init();
    }

    //  устанавливаем указатель менюшки на текущую роль
    public void prepareEditUser() {
        if (selectedUser.getRolename() != null) {
            this.selectedRole = selectedUser.getRolename();
        } else this.selectedRole = null;
    }

    //Запрашиваем список ролей для заполнения
    //выпадающего меню
    public List<Role> getAllRoles() {
        return userService.getAllRoles();
    }

    // Запрашиваем список пользователей из БД
    public List<User> getUsersList() {
        return this.usersList;
    }

    public User getSelectedUser() {
        return selectedUser;
    }

    public void setSelectedUser(User selectedUser) {
        this.selectedUser = selectedUser;
    }

    public Role getSelectedRole() {
        return selectedRole;
    }

    public void setSelectedRole(Role selectedRole) {
        this.selectedRole = selectedRole;
    }

    public void setUsersList(List<User> usersList) {
        this.usersList = usersList;
    }

    public void setUserService(UserService userService) {
        this.userService = userService;
    }
}

web/user/AddDesigner.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<ui:composition>

    <p:dialog header="Добавление проектировщика" widgetVar="DesignerAddDialog" modal="true" resizable="false" appendTo="@(body)">
        <h:form id="DesignersAddForm">
            <h:panelGrid columns="2" cellpadding="5">
                <h:outputText value="Фамилия"/>
                <p:inputText value="#{designerController.selectedDesigner.lastname}"/>


                <f:facet name="footer">
                    <p:commandButton value="Добавить" actionListener="#{designerController.addDesigner}"
                                     update=":formDesigners:tableDesigners"
                                     oncomplete="PF('DesignerAddDialog').hide();"/>
                    <p:commandButton value="Отменить" onclick="PF('DesignerAddDialog').hide();"/>
                </f:facet>
            </h:panelGrid></h:form>

    </p:dialog>

</ui:composition>
</html>

web/user/AddProject.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<ui:composition>

    <p:dialog header="Добавление проекта" widgetVar="ProjectAddDialog" modal="true" resizable="false" appendTo="@(body)">
        <h:form id="ProjectsAddForm">
            <h:panelGrid columns="2" cellpadding="5" rendered="#{projectController.tempProject != null}">
                <h:outputText value="Перечень объектов"/>
                <p:inputText value="#{projectController.tempProject.objects}"/>

                <h:outputText value="Название проекта"/>
                <p:inputText value="#{projectController.tempProject.title}"/>

                <h:outputText value="Заказчик"/>
                <p:inputText value="#{projectController.tempProject.customer}"/>

                <h:outputText value="Инвентарный номер"/>
                <p:inputText value="#{projectController.tempProject.invnum}"/>

                <h:outputText value="Библиотечный номер"/>
                <p:inputText value="#{projectController.tempProject.libnum}"/>

                <h:outputText value="Год"/>
                <p:inputText value="#{projectController.tempProject.year}"/>

                <h:outputText value="Реализован"/>
                <p:selectBooleanCheckbox value="#{projectController.tempProject.realised}"/>

                <h:outputText value="Проектировщик"/>
                <p:selectOneMenu value="#{projectController.selectedDesigner}">
                    <f:selectItems value="#{projectController.allDesigners}" var="list" itemLabel="#{list.lastname}"
                                   itemValue="#{list.id}"/>
                </p:selectOneMenu>

                <h:outputText value="Примечание"/>
                <p:inputTextarea value="#{projectController.tempProject.note}" rows="3" cols="33"/>

                <f:facet name="footer">
                    <p:commandButton value="Добавить" actionListener="#{projectController.addProject}"
                                     update=":formMain:tableProjects"
                                     oncomplete="PF('ProjectAddDialog').hide();"/>
                    <p:commandButton value="Отменить" onclick="PF('ProjectAddDialog').hide();"/>
                </f:facet>
            </h:panelGrid></h:form>

    </p:dialog>

</ui:composition>
</html>

web/user/DesignerList.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="#{loginController.template}">
    <ui:define name="title">
        <h:outputText value="Проектировщики"/>
    </ui:define>
    <ui:define name="body">
        <h:form id="formDesigners">
            <p:dataTable id="tableDesigners" value="#{designerController.designers}"
                         var="designers"
                         rows="20"
                         paginator="true"
                         paginatorPosition="top"
                         paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="10,20,30,50"
                         resizableColumns="true"
                         lazy="false"
                         paginatorAlwaysVisible="false"
                         selectionMode="single"
                         rowKey="#{designers.id}"
                         selection="#{designerController.selectedDesigner}">

                <p:ajax event="rowSelect" update="deleteButton editButton"/>
                <p:ajax event="rowUnselect" update="deleteButton editButton"/>

                <f:facet name="header">
                    Проектировщики
                </f:facet>
                <p:column headerText="Фамилия">
                    <h:outputText value="#{designers.lastname}"/>
                </p:column>

                <f:facet name="footer">
                    <p:commandButton id="createButton" icon="ui-icon-plus" value="Добавить"
                                     actionListener="#{designerController.prepareAddDesigner}"
                                     update=":DesignersAddForm"
                                     oncomplete="PF('DesignerAddDialog').show()"/>

                    <p:commandButton id="editButton" icon="ui-icon-pencil" value="Редактировать"
                                     update=":DesignersEditForm"
                                     oncomplete="PF('DesignerEditDialog').show()"
                                     disabled="#{empty designerController.selectedDesigner}"/>

                    <p:commandButton id="deleteButton" icon="ui-icon-trash" value="Удалить"
                                     actionListener="#{designerController.deleteDesigner}"
                                     update="tableDesigners,deleteButton"
                                     disabled="#{empty designerController.selectedDesigner}">
                        <p:confirm header="Удаление записи"
                                   message="Вы действительно хотите удалить проектировщика?"
                                   icon="ui-icon-alert"/>
                    </p:commandButton>
                </f:facet>
            </p:dataTable>
        </h:form>

        <ui:include src="/user/AddDesigner.xhtml"/>
        <ui:include src="/user/EditDesigner.xhtml"/>
    </ui:define>
</ui:composition>

</html>

web/user/EditDesigner.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<ui:composition>

    <p:dialog id="DesignerEditDlg" widgetVar="DesignerEditDialog" modal="true" resizable="false" appendTo="@(body)"
              header="Редактирование проектировщика">
        <h:form id="DesignersEditForm">
            <h:panelGroup id="display">
                <h:panelGrid columns="2" rendered="#{designerController.selectedDesigner != null}" cellpadding="5">
                    <h:outputText value="Фамилия"/>
                    <p:inputText value="#{designerController.selectedDesigner.lastname}"/>

                    <f:facet name="footer">
                        <p:commandButton actionListener="#{designerController.updateDesigner}" value="Изменить"
                                         update="display,:formDesigners:tableDesigners"
                                         oncomplete="PF('DesignerEditDialog').hide();" style="margin: 5px"/>
                        <p:commandButton value="Отменить" onclick="PF('DesignerEditDialog').hide();"/>
                    </f:facet>
                </h:panelGrid>
            </h:panelGroup>
        </h:form>
    </p:dialog>

</ui:composition>
</html>

web/user/EditFile.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<ui:composition>

    <p:dialog widgetVar="FileEditDialog" modal="true" resizable="false" appendTo="@(body)"  header="Редактирование файла">
        <h:form id="FileEditForm">
            <h:panelGroup id="FileEditGroup">
                <h:panelGrid id="FileEditPanel" cellpadding="5" columns="2">
                    <h:outputText value="Название файла:"/>
                    <p:inputText value="#{fileController.selectedFile.fname}"/>

                    <h:outputText value="Примечание:"/>
                    <p:inputTextarea value="#{fileController.selectedFile.note}" rows="3" cols="33"/>

                    <f:facet name="footer">
                        <p:commandButton actionListener="#{fileController.update}" value="Изменить"
                                         update="ProjectDetailsForm:tableFiles"
                                         oncomplete="PF('FileEditDialog').hide();" style="margin: 5px"/>
                        <p:commandButton value="Отменить" onclick="PF('FileEditDialog').hide();"/>
                    </f:facet>
                </h:panelGrid>
            </h:panelGroup>
        </h:form>
    </p:dialog>

</ui:composition>
</html>

web/user/EditProject.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<ui:composition>

    <p:dialog id="ProjectEditDlg" widgetVar="ProjectEditDialog" modal="true" resizable="false" appendTo="@(body)"
              header="Редактировать данные о проекте">
        <h:form id="ProjectEditForm">
            <h:panelGroup id="display">
                <h:panelGrid columns="2" rendered="#{projectController.tempProject != null}" cellpadding="5">
                    <h:outputText value="Перечень объектов"/>
                    <p:inputText value="#{projectController.tempProject.objects}"/>

                    <h:outputText value="Название проекта"/>
                    <p:inputText value="#{projectController.tempProject.title}"/>

                    <h:outputText value="Заказчик"/>
                    <p:inputText value="#{projectController.tempProject.customer}"/>

                    <h:outputText value="Инвентарный номер"/>
                    <p:inputText value="#{projectController.tempProject.invnum}"/>

                    <h:outputText value="Библиотечный номер"/>
                    <p:inputText value="#{projectController.tempProject.libnum}"/>

                    <h:outputText value="Год"/>
                    <p:inputText value="#{projectController.tempProject.year}"/>

                    <h:outputText value="Реализован"/>
                    <p:selectBooleanCheckbox value="#{projectController.tempProject.realised}"/>

                    <h:outputText value="Проектировщик"/>
                    <p:selectOneMenu value="#{projectController.selectedDesigner}">
                        <f:selectItems value="#{projectController.allDesigners}" var="list" itemLabel="#{list.lastname}"
                                       itemValue="#{list.id}"/>
                    </p:selectOneMenu>

                    <h:outputText value="Примечание"/>
                    <p:inputTextarea value="#{projectController.tempProject.note}" rows="3" cols="33"/>

                    <f:facet name="footer">
                        <p:commandButton actionListener="#{projectController.update}" value="Изменить"
                                         update="display,formMain:tableProjects"
                                         oncomplete="PF('ProjectEditDialog').hide();" style="margin: 5px"/>
                        <p:commandButton value="Отменить" onclick="PF('ProjectEditDialog').hide();"/>
                    </f:facet>
                </h:panelGrid>
            </h:panelGroup>
        </h:form>
    </p:dialog>

</ui:composition>
</html>

web/user/EditUser.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<ui:composition template="#{loginController.template}">
    <ui:define name="title">
        <h:outputText value="Редактирование данных"/>
    </ui:define>
    <ui:define name="body">
        <div>
            <p:panel id="panel" header="Заполните поля">
                <h:form>
                    <h:panelGrid columns="2" cellpadding="5">

                        <h:outputText value="Фамилия:"/>
                        <p:inputText value="#{loginController.currentUser.lastname}" required="true"
                                     requiredMessage="Требуется ввести значение"/>
                        <h:outputText value="Имя: "/>
                        <p:inputText value="#{loginController.currentUser.firstname}" required="true"
                                     requiredMessage="Требуется ввести значение"/>
                        <h:outputText value="Отчество: "/>
                        <p:inputText value="#{loginController.currentUser.middlename}" required="true"
                                     requiredMessage="Требуется ввести значение"/>
                        <h:outputText value="Логин: "/>
                        <p:inputText value="#{loginController.currentUser.name}" required="true"
                                     requiredMessage="Требуется ввести значение"/>
                        <h:outputText value="Пароль: "/>
                        <p:password id="pwd_input1" label="Password 1" value="#{loginController.currentUser.password}" match="pwd_input2"
                                    required="true"
                                    requiredMessage="Требуется ввести значение" validatorMessage="Пароли не совпадают"/>
                        <h:outputText value="Пароль повтор: "/>
                        <p:password id="pwd_input2" label="Password 2" value="#{loginController.currentUser.password}"
                                    required="true" requiredMessage="Требуется ввести значение"/>

                        <f:facet name="footer">
                            <p:commandButton value="Сохранить" action="#{loginController.updateUser}"
                                             update="growl,header-form-logedin"/>
                            <p:commandButton value="Cancel" update="panel" process="@this">
                                <p:resetInput target="panel"/>
                            </p:commandButton>
                        </f:facet>
                    </h:panelGrid>
                </h:form>
            </p:panel>
        </div>
    </ui:define>
</ui:composition>
</html>

web/user/ProjectDetails.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<ui:composition>
    <p:dialog id="ProjectDetailsDlg" widgetVar="ProjectDetailsDialog" modal="true" resizable="false" appendTo="@(body) "
              header="Детальная информация" width="80%">

        <h:form id="ProjectDetailsForm">
            <p:panelGrid columns="2" rendered="#{projectController.tempProject != null}">
                <h:outputText value="Название проекта:"/>
                <h:outputText value="#{projectController.tempProject.title}"/>

                <h:outputText value="Инвентарный номер:"/>
                <h:outputText value="#{projectController.tempProject.invnum}"/>

                <h:outputText value="Проектировщик:"/>
                <h:outputText value="#{projectController.curentDesignerLastname}"/>
            </p:panelGrid>

            <p:spacer/>

            <h:panelGroup id="display">
                <p:fieldset legend="Примечание" style="margin-bottom:20px">
                    <h:panelGrid columns="1" cellpadding="5">
                        <h:outputText styleClass="project-detail-note" value="#{projectController.tempProject.note}"/>
                    </h:panelGrid>
                </p:fieldset>

                <p:dataTable id="tableFiles" value="#{fileController.fileList}"
                             var="file"
                             rows="20"
                             paginator="true"
                             paginatorPosition="top"
                             paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             rowsPerPageTemplate="10,20,30,50"
                             resizableColumns="true"
                             lazy="false"
                             paginatorAlwaysVisible="false"
                             selectionMode="single"
                             rowKey="#{file.id}"
                             selection="#{fileController.selectedFile}">

                    <p:ajax event="rowSelect" update="deleteFileButton editFileButton downloadFileButton"/>
                    <p:ajax event="rowUnselect" update="deleteFileButton editFileButton downloadFileButton"/>

                    <f:facet name="header">
                        Файлы проекта
                    </f:facet>

                    <p:column headerText="Имя файла"
                              filterBy="#{file.fname}"
                              filterMatchMode="contains"
                              sortBy="#{file.fname}">
                        <h:outputText value="#{file.fname}"/>
                    </p:column>

                    <p:column headerText="Тип"
                              filterBy="#{file.contenttype}"
                              filterMatchMode="contains"
                              sortBy="#{file.contenttype}"
                              style="width:260px;">
                        <h:outputText value="#{file.contenttype}"/>
                    </p:column>

                    <p:column headerText="Размер (байт)"
                              filterBy="#{file.fsize}"
                              filterMatchMode="contains"
                              sortBy="#{file.fsize}"
                              style="width:160px;">
                        <h:outputText value="#{file.fsize}"/>
                    </p:column>

                    <p:column headerText="Примечание"
                              filterBy="#{file.note}"
                              filterMatchMode="contains"
                              sortBy="#{file.note}"
                              style="width:260px;">
                        <h:outputText value="#{file.note}"/>
                    </p:column>

                    <f:facet name="footer">
                        <p:commandButton id="createButton" icon="ui-icon-plus" value="Добавить"
                                         update=":FileAddForm"
                                         oncomplete="PF('FileAddDialog').show()"/>

                        <p:commandButton id="editFileButton" icon="ui-icon-pencil" value="Редактировать"
                                         update=":FileEditForm,editFileButton"
                                         oncomplete="PF('FileEditDialog').show()"
                                         disabled="#{empty fileController.selectedFile}"/>

                        <p:commandButton id="downloadFileButton" value="Скачать" ajax="false"
                                         icon="fa fa-fw fa-download" disabled="#{empty fileController.selectedFile}"
                                         update=":ProjectDetailsForm,growl"
                                         action="#{fileController.downloadSelectedFile}">
                        </p:commandButton>

                        <p:commandButton id="downloadAllFilesButton" value="Скачать архив" ajax="false"
                                         icon="fa fa-fw fa-file-zip-o"
                                         disabled="#{empty fileController.fileList}"
                                         update=":ProjectDetailsForm,growl"
                                         action="#{fileController.downloadAllFiles()}">
                        </p:commandButton>

                        <p:commandButton id="deleteFileButton" icon="ui-icon-trash" value="Удалить"
                                         actionListener="#{fileController.deleteFile}"
                                         update=":ProjectDetailsForm:tableFiles,deleteFileButton"
                                         disabled="#{empty fileController.selectedFile}"/>
                    </f:facet>
                </p:dataTable>
            </h:panelGroup>
        </h:form>
    </p:dialog>

    <p:dialog modal="true" widgetVar="statusDialog" draggable="false" closable="true" resizable="false"
              showHeader="false" appendTo="@(body)">
    </p:dialog>

    <p:dialog id="FileAddDlg" widgetVar="FileAddDialog" modal="true" resizable="false" appendTo="@(body)"
              header="Добавить файл">
        <h:form id="FileAddForm">
            <p:fileUpload
                    fileUploadListener="#{fileController.addFileToAttachment}"
                    uploadLabel="Загрузить на сервер"
                    cancelLabel="Отмена"
                    label="Выберните файл"
                    update="growl, :ProjectDetailsForm:tableFiles"
                    multiple="true"
                    mode="advanced"
                    description="Select file"/>
        </h:form>
    </p:dialog>

    <ui:include src="/user/EditFile.xhtml"/>
</ui:composition>
</html>

web/user/UserMenu.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

<ui:composition>
    <p:submenu label="Меню" expanded="true">
        <p:menuitem value="Проекты" action="/user/ProjectList" icon="ui-icon-menuitem"/>
        <p:menuitem value="Проектировщики" action="/user/DesignerList" icon="ui-icon-menuitem"/>
        <p:menuitem value="Редактирование своих данных" action="/user/EditUser" icon="ui-icon-menuitem"/>
    </p:submenu>
</ui:composition>
</html>

web/user/UserTemplate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<ui:composition template="/template.xhtml">
    <ui:define name="title">
        <h:outputText value="Режим пользователя"/>
    </ui:define>
    <ui:define name="left_menu">
        <h:form id="form_menu">
            <p:panelMenu>
                <ui:include src="/user/UserMenu.xhtml"/>
            </p:panelMenu>
        </h:form>
    </ui:define>
</ui:composition>
</html>